### ISSUE TITLE
Ubuntu18 crashes and reboots while training on only_known_train

### ISSUE THREAD

**Issue by dkaberna** [radekosmulski/whale#10]
Quick question - when running your only_known_train notebook in jupyter, my entire O/S crashes and reboots after saving res50-full-train-stage-2 but before the 3rd.  I have the 1080 TI with 11GB, and as I was monitoring it before it crashed, it hadn't fully peaked on memory usage yet, so I'm a bit bewildered.  I haven't checked server logs yet.  Do you suggest I scale back on one of the following:

1.) Image size
2.) batch size

or both?  Which should I start reducing first, in your opinion?

**Comment by radekosmulski** [comment]
Sounds like it might be a hardware issue. Have you done any training on this machine before or is this the first time you are using it under such load? This does not seem to be code related. Also, has it only crashed once or have you tried re-running the training?

**Comment by dkaberna** [comment]
You’re probBly right. It’s crashed twice in this notebook at same spot.
I’ve run the other fastai notebooks, and will occasionally get a out of
memory message, but no crash. Will continue to investigate.

**Comment by radekosmulski** [comment]
If you run `nvidia-smi -l` from terminal this will show you gpu load. If this would happen only when GPU is under full load (check 'Volatile GPU-Util' and 'GPU Fan' / 'temp'), this might indicate a cooling or a power supply issue.

**Comment by dkaberna** [comment]
Thank you for your help.  I realize this issue isn't truly a "bug" within your code - more that of me reaching for help!  :)  Appreciate the mentorship.

**Comment by radekosmulski** [comment]
np at all - best of luck in troubleshooting this, if you find you have trouble figuring out what is going on you might want to stop by the fastai forums - a lot of people there really into hw so might be able to help
