### ISSUE TITLE
MAP@5

### ISSUE THREAD

**Issue by jidroid404** [radekosmulski/whale#11]
Can something give an intuitive explanation of what this evaluation metric actually is and what it signifies?

**Comment by radekosmulski** [comment]
Hi @jidroid404! Generally issues are best used for reporting issues with code in the repo - such questions are better to ask in Kaggle forums.

As for the metric, its is mean average precision evaluated looking at top 5 predictions.

Say we are predicting fruit type from 20 possible categories. If the ground truth label is 'apple' and our most likely prediction is 'apple', we get a full point for this prediction. If, however our prediction looks like this: ['orange', 'apple', ..., ..., ...] we get some fraction of the point. If we predict apple among the 5 most likely categories, we get some fraction of a point, the further from the first place the prediction, the smaller the fraction. If we don't include 'apple' in top5 most likely categories, we get 0.

Hope this helps. If you are looking for further information, the name is 'mean average precision' and googling for this should return a lot of results. Best of luck.
