### ISSUE TITLE
create_submission function?

### ISSUE THREAD

**Issue by matthewarthur** [radekosmulski/whale#12]
Can you provide more information on the create_submission() function you are calling? How are you processing the output tensors?

**Comment by arcile** [comment]
matthewarthur, I'm not figuring this one out either! What did you do to get it working?

**Comment by arcile** [comment]
> @matthewarthur , I'm not figuring this one out either! What did you do to get it working?

So to answer my own question, if someone else has the same question (I'm using a Google Cloud jupyter notebook).

To get the createsubmission function to work, you need to put the utils.py file (also in radeks repository) in the same folder as your notebook file (.ipynb). The createsubmission() function is defined in utils.py
