### ISSUE TITLE
TypeError: image2tensor() got an unexpected keyword argument 'augment_fn' in classification_and_metric_learning notebook

### ISSUE THREAD

**Issue by dkaberna** [radekosmulski/whale#15]
Hi, when I run your code block #18 (shown below) from classification_and_metric_learning.ipynb, I get an error message shown below this code block:

 %%time
SZ = 224
NUM_WORKERS = 12
BS = 32

basic_dataloader = create_basic_dataloader(SZ, NUM_WORKERS, BS)
dists = create_similarity_dict(learn.model, basic_dataloader)
data = create_data(SZ, dists, BS)

Error message:
TypeError: Traceback (most recent call last):
  File "/home/devon/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/devon/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/devon/fastai/kaggle/whale/zen_dataset/zen_dataset/dataset.py", line 10, in __getitem__
    return self.reader(item), self.labeler(item)
  File "<ipython-input-9-6166f5905b60>", line 8, in __call__
    tensors = [image2tensor(image, augment_fn = self.augment_fn) for image in images]
  File "<ipython-input-9-6166f5905b60>", line 8, in <listcomp>
    tensors = [image2tensor(image, augment_fn = self.augment_fn) for image in images]
TypeError: image2tensor() got an unexpected keyword argument 'augment_fn'

Here's my env:
=== Software === 
python        : 3.6.8
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 410.104
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11175MB | GeForce GTX 1080 Ti

=== Environment === 
platform      : Linux-4.15.0-46-generic-x86_64-with-debian-buster-sid
distro        : Ubuntu 18.04 bionic
conda env     : fastai
python        : /home/devon/anaconda3/envs/fastai/bin/python
sys.path      : 
/home/devon/anaconda3/envs/fastai/lib/python36.zip
/home/devon/anaconda3/envs/fastai/lib/python3.6
/home/devon/anaconda3/envs/fastai/lib/python3.6/lib-dynload
/home/devon/.local/lib/python3.6/site-packages
/home/devon/anaconda3/envs/fastai/lib/python3.6/site-packages
/home/devon/fastai/kaggle/whale/zen_dataset
/home/devon/fastai

Sun Mar 24 19:51:37 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  0%   55C    P8    21W / 280W |   1616MiB / 11175MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2243      G   /usr/lib/xorg/Xorg                            46MiB |
|    0      2313      G   /usr/bin/gnome-shell                          49MiB |
|    0      6726      G   /usr/lib/xorg/Xorg                           475MiB |
|    0      6881      G   /usr/bin/gnome-shell                         229MiB |
|    0      7580      G   ...quest-channel-token=2872686570769991275   151MiB |
|    0     12588      G   /usr/bin/python3                              31MiB |
|    0     31856      C   .../devon/anaconda3/envs/fastai/bin/python   627MiB |
+-----------------------------------------------------------------------------+

```

I know it's an environment issue and NOT an issue with your code.  Was hoping to get some advice on this.  Thanks so much

**Comment by radekosmulski** [comment]
Hi Devon,

This turned out to be an issue with my code after all :slightly_smiling_face: Turns out I forgot to push changes to `zen_dataset`. Could you please pull from the repo and try again?

Let me please know if this resolves it for you and sorry about the trouble

**Comment by dkaberna** [comment]
Will do!  Thank you for fixing!  Would it be asking too much if you could paste below your environment so I can verify if I setup mine? 

I'm traveling until Thursday, so I won't be able to verify until.  So in the meantime, I will close out this issue so it's not lingering on your dashboard. :)

**Comment by radekosmulski** [comment]
Sure, no problem at all :) Could you please let me know what command you would like me to run to get the env printout?

Happy to provide it. From experience though what seemed to be most crucial was getting the right version of fastai since the API is changing so quickly.

**Comment by dkaberna** [comment]
This is what I had run for you: python -m fastai.utils.show_install 1

Agree with what you said.  Troubleshooting other issues when I ran your notebooks was dependent on fastai versions.  Thanks for sharing your work with others!  It's so helpful.

**Comment by radekosmulski** [comment]
Glad you are finding this useful :slightly_smiling_face: 

Here is the output of the command:
```text
=== Software === 
python        : 3.7.0
fastai        : 1.0.49.dev0
fastprogress  : 0.1.20
torch         : 1.0.0
nvidia driver : 410.104
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11177MB | GeForce GTX 1080 Ti

=== Environment === 
platform      : Linux-4.4.0-143-generic-x86_64-with-debian-stretch-sid
distro        : Ubuntu 16.04 Xenial Xerus
conda env     : fastai_n
python        : /home/radek/anaconda3/envs/fastai_n/bin/python
sys.path      : /home/radek
/home/radek/anaconda3/envs/fastai_n/lib/python37.zip
/home/radek/anaconda3/envs/fastai_n/lib/python3.7
/home/radek/anaconda3/envs/fastai_n/lib/python3.7/lib-dynload
/home/radek/anaconda3/envs/fastai_n/lib/python3.7/site-packages
/home/radek/anaconda3/envs/fastai_n/lib/python3.7/site-packages/fast_progress-0.1.3-py3.7.egg
/home/radek/workspace/fastai
/home/radek/workspace/zen_dataset

Tue Mar 26 10:55:19 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:26:00.0 Off |                  N/A |
|  0%   41C    P5    26W / 280W |      0MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
