### ISSUE TITLE
cannot find your zen_dataset module

### ISSUE THREAD

**Issue by Horace89** [radekosmulski/whale#18]
Hi Radek,
In the `extract_bboxes.ipynb` and `classification_and_metric_learning.ipynb` notebooks you use the zen_dataset library, but it seems that you have deleted it.

Could I get a copy so that I can run these notebooks?

**Comment by radekosmulski** [comment]
oh dear, I don't have it anywhere! I completely forgot it was being used anywhere

I will ask on Twitter, maybe someone still has it - very sorry for this inconvenience, fingers crossed someone still has it

note to self: do not delete repositories, best to make them private for clean up purposes...

**Comment by radekosmulski** [comment]
Turns out one can restore a deleted repository on github! :partying_face: 

Restore in progress, should take around an hour. Let me know please how it goes

**Comment by Horace89** [comment]
thanks a lot! I find your code very clean and instructive, so I'm really looking forward to this! 👍 
I'll tell you if everything goes well.

**Comment by radekosmulski** [comment]
thank you @Horace89 for your kind words, really glad you are finding this useful 🙇

**Comment by Horace89** [comment]
Hey @radekosmulski , everything seems to be ok now. I've included the code directly in my notebooks, and now they can proceed. I'm currently running `classification_and_metric_learning.ipynb` and I'm waiting for the line `data = create_data(SZ, dists, BS)` to finish.

Again, thanks a lot ! 👍

**Comment by radekosmulski** [comment]
Thank you @Horace89 for the update! Really happy to hear
