### ISSUE TITLE
error in the data.show_batch

### ISSUE THREAD

**Issue by theSha1do1w** [radekosmulski/whale#2]
i got error in the below code
`data.show_batch(rows=3)`
the error is 
RuntimeError : DataLoader worker (pid 38) is killed by signal: Bus error. 

Thanks in advance for your help!

**Comment by radekosmulski** [comment]
Could you try running this with NUM_WORKERS=0? This should give a better error message.

**Comment by theSha1do1w** [comment]
Thanks i have solved this but i can't download the pretrained model in the kaggle kernel.Because of the limit of the read only file.But i can download the pretrained model with fastai V0.7.0.Do you know how to solve it?Thanks again.

**Comment by radekosmulski** [comment]
No, I don't.

**Comment by wyj2046** [comment]
same error in first submission data.show_batch()
It raise ValueError: padding_mode needs to be 'zeros' or 'border', but got reflection

**Comment by wyj2046** [comment]
> same error in first submission data.show_batch()
> It raise ValueError: padding_mode needs to be 'zeros' or 'border', but got reflection

just update pytorch to 1.0 solve this problem
