### ISSUE TITLE
When did you save "'small_lr'

### ISSUE THREAD

**Issue by xuzhang5788** [radekosmulski/whale#4]
Thank you so much for your work. I followed your instruction and ran every notebooks and got a score of 0.754.
When I ran "only_known_research.ipynb", I couldn't find a file called "small_lr.pth". I just comment out  learn.load('small_lr') and continued to train until the end without any problems.

**Comment by radekosmulski** [comment]
Happy to hear that! I made a change to the notebook - commenting out the line should no longer be required and it should be easier to follow.

Thx for the heads up on this.

**Comment by xuzhang5788** [comment]
@radekosmulski Thank you so much for your fast reply. May I ask you why you do the following code twice when you start to train the model?

learn = create_cnn(data, models.resnet50, metrics=[accuracy, map5], lin_ftrs=[2048])
learn.clip_grad();

learn.fit_one_cycle(12, 1e-2)

learn.unfreeze()

max_lr = 1e-3
lrs = [max_lr/100, max_lr/10, max_lr]

learn.fit_one_cycle(20, lrs)

**Comment by radekosmulski** [comment]
I might initially be training on smaller images and later training on larger images. I am not sure which part of the notebook you are referring to.

Apologies, closing this. For any discussions on what the code does please go to the [kaggle thread](https://www.kaggle.com/c/humpback-whale-identification/discussion/74647)
