### ISSUE TITLE
error while training

### ISSUE THREAD

**Issue by tirtile** [radekosmulski/whale#6]
i got error in the below code
learn.fit_one_cycle(2) after finish first cycle 
the error is
RuntimeError: Could not infer dtype of NoneType

Thanks in advance for your help!

**Comment by radekosmulski** [comment]
In which notebook are you getting this error? Could you please check which version of the library are you using? (instructions how to get the library version are in the readme - it is important that you are on the correct one).

**Comment by radekosmulski** [comment]
closing due to no reply
