### ISSUE TITLE
a error in siamese_prototype

### ISSUE THREAD

**Issue by joinssmith** [radekosmulski/whale#7]
fastai version '1.0.36.post1'
In fact, 1.0.39 doesn't work either.

in Predict part

```
data = (
    ImageItemList
        .from_df(df, 'data/train_crop', cols=['Image'])
#         .no_split()
        .split_by_valid_func(lambda path: path2fn(path) in {'69823499d.jpg'}) # in newer version of the fastai library there is .no_split that could be used here
        .label_from_func(lambda path: fn2label[path2fn(path)], classes=classes)
        .add_test(ImageItemList.from_folder('data/test_crop'))
        .transform(tfms=None, size=SZ, resize_method=ResizeMethod.SQUISH)
        .databunch(bs=BS, num_workers=NUM_WORKERS, path='data')
        .normalize(imagenet_stats)
)
```

creating data appear:
UserWarning: It's not possible to collate samples of your dataset together in a batch.

and it showed:
Shapes of the inputs/targets:
[[torch.Size([3, 349, 998]), torch.Size([3, 304, 797]), torch.Size([3, 258, 986]), torch.Size([3, 298, 970]), torch.Size([3, 176, 589]), torch.Size([3, 368, 1042]), torch.Size([3, 167, 651]), torch.Size([3, 314, 1024]), torch.Size([3, 238, 1044]), torch.Size([3, 506, 1004]), torch.Size([3, 340, 921]), torch.Size([3, 290, 966]), torch.Size([3, 270, 1010]), torch.Size([3, 329, 529]), torch.Size([3, 264, 941]), torch.Size([3, 411, 848]), torch.Size([3, 417, 1018]), torch.Size([3, 180, 891]), torch.Size([3, 274, 926]), torch.Size([3, 406, 995]), torch.Size([3, 339, 1009]), torch.Size([3, 238, 1031]), torch.Size([3, 221, 805]), torch.Size([3, 200, 573]), torch.Size([3, 299, 1018]), torch.Size([3, 319, 1042]), torch.Size([3, 408, 1014]), torch.Size([3, 184, 957]), torch.Size([3, 375, 1009]), torch.Size([3, 410, 1024]), torch.Size([3, 472, 911]), torch.Size([3, 226, 695])], [(), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), ()]]

and next code
```
test_feats = []
learn.model.eval()
for ims, _ in data.test_dl:
    test_feats.append(learn.model.process_features(learn.model.cnn(ims)).detach().cpu())
```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 303 and 370 in dimension 2 at ...

And like I'm the only one who has this problem? Maybe I used the cropped image? I don't think so.
And the previous two attempts to create data worked fine.Do I need to convert all images to RGB?

**Comment by radekosmulski** [comment]
Yes, your input data needs to be resized and all images need to be in RGB (the error msg that you shared indicates that only resizing is the problem). Once you resize your data using the `resize.ipynb` notebook everything should be okay.

**Comment by joinssmith** [comment]
Thank you very much!

As well as a small problem, the use of 'num_work' on win10 often causes 'broken pipe', but sometimes it doesn't happen, although it can still be trained by changing to 0, but I wonder how this can be solved?

**Comment by radekosmulski** [comment]
I do not know unfortunately. I have never used win10.
