### ISSUE TITLE
use of new_whale_idx in siamese_network_prototype.ipynb:

### ISSUE THREAD

**Issue by SwatiTiwarii** [radekosmulski/whale#8]

**Comment by SwatiTiwarii** [comment]
Hi Radek,

I have been trying to replicate your work from Siamene Network notebook. I have doubt regarding following code snippet: 

`%%time
top_5s = []
for i, sim in enumerate(sims):
    idxs = sim.argsort(descending=True)
    probs = sim[idxs]
    top_5 = []
    for j, p in zip(idxs, probs):
        if len(top_5) == 5: break
        if j == new_whale_idx or j == i: continue
        predicted_class = data.valid_ds.y.items[j]
        if predicted_class not in top_5: top_5.append(predicted_class)
    top_5s.append(top_5)`
Why are we  checking: **j == new_whale_idx**  in the inner for loop , if we want to check whether our prediction is suggesting index of 'new_whale' we should put it after calculating predicted_class in next line. 


`%%time
top_5s = []
for i, sim in enumerate(sims):
    idxs = sim.argsort(descending=True)
    probs = sim[idxs]
    top_5 = []
    for j, p in zip(idxs, probs):
        if len(top_5) == 5: break
        if j == i: continue  
        predicted_class = data.valid_ds.y.items[j]
        if predicted_class == 3: continue
        if predicted_class not in top_5: top_5.append(predicted_class)
    top_5s.append(top_5)`

Let me know in case i am missing something.

**Comment by radekosmulski** [comment]
Reading the code, I think `j` is the index of the predicted class and `predicted_class` is the label. Assuming this is correct (and I can't run the code right now to verify) we want to be comparing `j` with the `new_whale_idx` and not `predicted_class` (in the case where `j` == `new_whale_idx`, `predicted_class` should equal `'new_whale'`)

**Comment by SwatiTiwarii** [comment]
![image](https://user-images.githubusercontent.com/46405184/51110541-0cd74c80-181f-11e9-8890-640a78c43edf.png)


**sims** is 3570  X 3570 matrix , where sims[0] contains similarity score with each of the image present in the validation dataset . Therefore , the indices  under consideration **for  j , p in  [idxs , probs]**  are indices for images present in the validation data set ( and hence can not be compared with new_whale_idx) .

**Comment by radekosmulski** [comment]
Yes, indeed, you are right! Well spotted and thx for letting me know about this. Will fix this

**Comment by SwatiTiwarii** [comment]
Thanks Radek : )
