### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by dkaberna** [radekosmulski/whale#9]
Hello,

First, thank you so VERY MUCH for uploading your code to GitHub.  This has been very helpful for me.

I am getting an error when running first_submission.  I get this error, shown below.  I confirmed I am running correct fastai version.  

I'm running:
nvidia driver ver 415.27
cuda version 10.0.
anaconda ver 1.7.2

Not sure if these conflict with what you did.

Any ideas?

IndexError: Traceback (most recent call last):
  File "/home/devon/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/devon/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/devon/fastai/fastai/data_block.py", line 492, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/devon/fastai/fastai/data_block.py", line 92, in __getitem__
    if isinstance(try_int(idxs), int): return self.get(idxs)
  File "/home/devon/fastai/fastai/vision/data.py", line 265, in get
    fn = super().get(i)
  File "/home/devon/fastai/fastai/data_block.py", line 58, in get
    return self.items[i]

**Comment by dkaberna** [comment]
I'm running nvidia driver ver 415.27 and cuda version 10.0.  Not sure if this conflicts with what you did.

**Comment by dkaberna** [comment]
Please disregard. Was my own error.

**Comment by jandremarais** [comment]
@dkaberna do you mind sharing what went wrong here and how you fixed it? Facing a similar issue ATM.

**Comment by dkaberna** [comment]
I think I had forgotten to save the test and training data correctly.  Which block of code are you getting this error?

**Comment by jandremarais** [comment]
No never mind. I'm following the same approach as in the siamese notebook (ImageItemList -> Custom Dataset -> DataLoader -> DataBunch) but with some other tweaks. But maybe our errors are unrelated, so I will work on it some more to get to the bottom of it. Thanks anyways.

**Comment by jandremarais** [comment]
No never mind. I'm following the same approach as in the siamese notebook (ImageItemList -> Custom Dataset -> DataLoader -> DataBunch) but with some other tweaks. But maybe our errors are unrelated, so I will work on it some more to get to the bottom of it. Thanks anyways.
